import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styles1 from '../styles/Home1.module.css'
import styles2 from '../styles/Home2.module.css'
import styles3 from '../styles/Home3.module.css'
import styles4 from '../styles/Title.module.css'
import Blog from '../styles/Blog.module.css'

export default function Home() {
  return (

<div className={styles.container}>
       <Head>
        <title className={styles4.con}>
          Hunting Coder
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      
      {/* <script src='sc.js' strategy ="lazyOnload" ></script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>

        <p className={styles.description}>
          A blog for hunting coder by a hunting coder.
        </p>

        <div className={styles1.con}>
          <h2>"Popular Blogs"</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn php in 2022?</h3>
            <p>JavaScript is the language used to design logic for web.</p>
          </div> 
          <div className="blogItem">
            <h3>How to python in 2022?</h3>
            <p>JavaScript is the language used to design logic for web.</p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
